services:
  - type: web
    name: camp-sol-taplin-dashboard-live
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: CAMPMINDER_API_KEY
        sync: false
      - key: CAMPMINDER_SUBSCRIPTION_KEY
        sync: false
      - key: CAMPMINDER_SEASON_ID
        value: "2026"
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.0"
